### PR TITLE
Add identifiers to the report metadata section

### PR DESCRIPTION
**Pull request by rgreinho**
This patch adds 2 identifiers to the report metadata section:
- a scan id, which which allows to identify a specific scan run
- a URL to ensure we know where the report was generated from

The main use case behind this patch is to be able to use the reports
without having to add extra context. For now we agreed on a convention
to name the report file as `{owner}-{repo}-{timestamp}.json`, but this
information gets lost when the content of the repost is simply shared
via email or pastebin.

### CODE REVIEW

**Comment by rgreinho** [comment]
Looks like `coverage` is not very happy right now:

```
Run codecov/codecov-action@v2
  with:
==> linux OS detected
Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1502:34)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:711:12)
```

**Comment by naortalmor1** [comment]
hi @itaywol  can you help with the this?

**Comment by rgreinho** [comment]
@naortalmor1 @itaywol it looks like all the tests passed now 👍 Ready to review?

**Comment by naortalmor1** [comment]
Yep on it

**Review by naortalmor1 — APPROVED** [review]

**Comment by naortalmor1** [comment]
Hi @rgreinho thanks for contributing! Merged (:

**Pull request merged**
